### ISSUE TITLE
Simplify parse-response using map

### ISSUE THREAD

**Issue by saurabh-ku** [ThatGuyHughesy/creddit#19]
In the function `parse-response` we are using reduce to get the inner data from the list of posts returned from the API. 

```clojure
(defn- parse-response
  [response]
  (if-let [data (or (get-in response [:data :children])
                    (get-in response [:data :trophies]))]
    (reduce
      (fn [posts post]
        (conj posts (:data post)))
      []
      data)
    (:data response)))
```

This code can be simplified using map instead of reduce

```clojure
(defn- parse-response
  [response]
  (if-let [coll (or (get-in response [:data :children])
                    (get-in response [:data :trophies]))]
    (map :data coll)
    (:data response)))
```

This can make the code a little more readable. Also renaming the variable will make it more obvious that we are dealing with a collection of values. What do you think?

**Comment by ThatGuyHughesy** [comment]
Hey @saurabh-ku 😄 

Yes absolutely, I think your changes are definitely an improvement.

**Comment by saurabh-ku** [comment]
Hey I raised a PR for this. Please review it.
