### ISSUE TITLE
URL functions instead of hard coded strings

### ISSUE THREAD

**Issue by saurabh-ku** [ThatGuyHughesy/creddit#21]
In each of our wrapper functions we are calling the `http-get` method with a hard coded string for the API URL.

```clojure
(http-get credentials (str "https://www.reddit.com/.json?limit=" limit "&t=" (name time))
```

Here are some different approaches that we could take
1. Custom function for each URL
```clojure
(http-get credentials (str (url/subreddit "aww") "?limit=" limit "&t=" (name time))
```

2. Decorative functions
```clojure
(-> reddit
      (subreddit "awww')
      (limit 1)
      (time :hour))
```
The reddit function creates the base url and each function then decorates on top of it
With this approach we might not need to create custom url for each endpoint, instead we just need a small set of decorators.
The con is that it will be difficult to manage invalid URLs, not sure how to handle that.

3. Create a custom DLS like hiccup
```clojure
[:reddit
  [:subreddit "aww"]
  [:limit 1]
  [:time :hour]]
```
Works out same as the decorative model but this allows for easy algorithmic url creation. This is very suitable of the url is to be created at run time. Might be a lot of fun to build as well.

The reason I am suggesting this change is that in all of our wrapper functions the only thing that is different is the URL for the API and creating a custom wrapper function for each endpoint might not be scalable.

With functions that generate url we can change the client to look something like this

```clojure
(defn reddit-client [cred url]
  (-> (http-get cred (build-url url))
        (process-response))
```
And the usage would be something like this

```clojure
(reddit-client 
      cred  
      [:reddit
          [:subreddit "aww"]
          [:limit 1]
          [:time :hour]])
```

1. In the decorative model supporting new URL's will be easier and much more reuse-able. 
2. URL's can be stored since they are merely data allowing for more flexibility
3. Makes the process a little more pure 

What are your thoughts on it?

**Comment by saurabh-ku** [comment]
another simpler approach would be to accept it as a map
```clojure 
{ :subreddit "aww"
  :limit 1
  :time :hour}
```

This would be much simpler to implement than a custom DSL I suppose and will give similar flexibility

**Comment by ThatGuyHughesy** [comment]
You bring up some good points, especially:

> creating a custom wrapper function for each endpoint might not be scalable.

This is a valid point, having thought about it I think the best first step could be to consolidate the functions i.e. `subreddit-controversial`, `subreddit-new`, `subreddit-rising` etc... into to `(subreddit :new ....)`?

We could then pass in limit/time as an optional map?

```
(defn subreddit 
  ([endpoint subreddit] ....)
  ([endpoint subreddit options] ....))

(subreddit :new "awww" {:limit 1 :time :hour})
(subreddit :about "awww")
```

I also agree about a function for building the url to remove all the hardcoded strings in each function.

**Comment by saurabh-ku** [comment]
I like the design of having separate functions as it makes the api more obvious to the user, but was just wondering if there would be too much duplicate code between these functions as they will be doing simple string concatenation. 

Let me prototype some of these designs so that we can decide better.

**Comment by ThatGuyHughesy** [comment]
That's true, the separate functions are a lot more intuitive. I guess when you look at multiple functions where the only different between them is a tiny of part of a URL you wonder whether they should be refactored or consolidated!

Sounds good! Looking forward to it 😃

**Comment by saurabh-ku** [comment]
```clojure
(defn- http-get' [credentials url query]
  (-> (client/get url
                  {:basic-auth [(:access-token credentials)]
                  :headers {"User-Agent" "creddit"}
                  :socket-timeout 10000
                  :conn-timeout 10000
                  :query query
                  :as :json})
      (get :body)))

(def list-by-to-str
  {:hot           "hot"
   :new           "new"
   :controversial "controversial"
   :rising        "rising"
   :top           "top"})

(defn subreddit'
  [sub list-by]
    (let [list-by-str (list-by list-by-to-str "")]
      (str "https://www.reddit.com/r/" sub "/" list-by-str "/.json")))

(defn reddit-client
  [credentials url options]
    (let [limit (:limit options "")
          time  (:time options "")
          query {"limit" limit "time" time}]
      (-> (http-get' credentials url query)
          parse-response)))
```

By moving the options into http-get since they are only query parameters we can get a much more simple url function.
