### ISSUE TITLE
Support User Actions

### ISSUE THREAD

**Issue by xivh** [ThatGuyHughesy/creddit#25]
User actions aren't currently supported, such as [submit](https://www.reddit.com/dev/api/#POST_api_submit).

I created #24 as an example with the submit endpoint, but there are a lot more available. There also needs to be a way to refresh the token. I'm not experienced with Clojure so if you could take a look at my code and give me some feedback that would be great, and I can add more endpoints if #21 hasn't been implemented yet.

**Comment by ThatGuyHughesy** [comment]
Ideally I think it would be great if we could automatically refresh the token if the access token has expired or at the very least expose a `refresh-token` function to the user which they can call if it has expired.

We store `expires-in` so before every API call we could simply check if this timestamp has passed and refresh the token if it has?

As for adding more endpoints, absolutely, go ahead!

**Comment by xivh** [comment]
Ok, I'll work on more endpoints and also figure out how to make unit tests.
