### ISSUE TITLE
Consider merging PR #27 -- Feature/post comment search before after

### ISSUE THREAD

**Issue by OliverAndrews** [ThatGuyHughesy/creddit#28]
Hi all, I have outstanding PR which I think complies to the contributing guidelines. @ThatGuyHughesy, would you consider merging this into the master of this project?

**Comment by ThatGuyHughesy** [comment]
Hi @OliverAndrews, sorry for the delay, for some reason I did not receive any notifications for your pull request or this issue. I have merged your code, thanks for contributing!
